### ISSUE TITLE
Submission search download cannot be unzipped

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#469] opened 2015-06-21 01:32 UTC
When downloading the ZIP archive of a submission search, the following error occurs:

```
Archive:  submission-query.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of submission-query.zip or
        submission-query.zip.zip, and cannot find submission-query.zip.ZIP, period.
```

**Comment by Sumukh** [comment] 2015-06-21 01:34
Duplicate of #462

**Closed** 2015-06-21 01:34 UTC
Labels: bug
