### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#383] opened 2015-02-18 23:51 UTC
Here are some suggestions on how to improve the UI:
* Clicking on the logo in the top left should bring me to the homepage.
* Clicking on an assignment in the sidebar should scroll to that assignment in the page.
* The header should have a background so it doesn't get covered up when you scroll down.
* The menu that appears on the right should be replaced with a simple dropdown that appears when the user hovers over the header.
* Lists (list of courses, list of assignments) should take up less space. Currently each item takes up over half my screen height, and getting to any one item or browsing requires too much scrolling.
* Each assignment should have a separate page. The assignment page could list submissions, backups, and groups, perhaps using tabs so they can be listed easily.
* There should be a breadcrumb in the header to help navigate, similar to Gradescope's. The breadcrumb has the form Course > Assignment and the Assignment has a dropdown allowing you to navigate to other assignments in the same class easily.
* The user should be notified in real time when they or someone in their group submits or adds them to a group.
* Each assignment should link to the relevant description e.g. maps should link to http://cs61a.org/proj/maps/.

**Comment by Some3141** [comment] 2015-02-19 06:03
Here's my take on them. Also, in the future, can you make a separate issue for each suggestion? It might be kinda spammy, but it keeps the discussion in 1 place for each issue.

- Clicking on the logo in the top left should bring me to the homepage.
   - Agreed. Made an issue for it.
- Clicking on an assignment in the sidebar should scroll to that assignment in the page.
   - Duplicate of #375 
- The header should have a background so it doesn't get covered up when you scroll down.
   - Agreed. Made an issue for it.
- The menu that appears on the right should be replaced with a simple dropdown that appears when the user hovers over the header.
   - I don't like the hovering because it might be unintentional and annoying. I think they should have to click on stuff to show intent.
- Lists (list of courses, list of assignments) should take up less space. Currently each item takes up over half my screen height, and getting to any one item or browsing requires too much scrolling.
   - I don't think it should take up less space- I don't like having a large information density for the student view. If we bubble up active assignments, scrolling goes away.
- Each assignment should have a separate page. The assignment page could list submissions, backups, and groups, perhaps using tabs so they can be listed easily.
  - There's no need for separate pages for assignments. You really only care about your most recent backups, etc. If there's too much information, this gets annoying to navigate (and I get a ton of UI complaints).
- There should be a breadcrumb in the header to help navigate, similar to Gradescope's. The breadcrumb has the form Course > Assignment and the Assignment has a dropdown allowing you to navigate to other assignments in the same class easily.
  - Not sure if this is necessary without the previous bullet point.
- The user should be notified in real time when they or someone in their group submits or adds them to a group.
  - Yes, this is in the works. (The notification framework will be able to handle this).
- Each assignment should link to the relevant description e.g. maps should link to http://cs61a.org/proj/maps/
   - Agreed. This is also in the works.

**Comment by Some3141** [comment] 2015-02-19 06:04
I'll close this issue unless you think my reasoning is wrong for some of the UI choices I disagreed with you on.

**Comment by Sumukh** [comment] 2015-02-19 06:07
@knrafto - were you referring to email notifications for partner signups - or just a notification on the site ?

**Comment by knrafto** [comment] 2015-02-22 23:43
* The menu that appears on the right should be replaced with a simple dropdown that appears when the user hovers over the header.
I don't like the hovering because it might be unintentional and annoying. I think they should have to click on stuff to show intent.
Lists (list of courses, list of assignments) should take up less space. Currently each item takes up over half my screen height, and getting to any one item or browsing requires too much scrolling.
I don't think it should take up less space- I don't like having a large information density for the student view. If we bubble up active assignments, scrolling goes away.
Each assignment should have a separate page. The assignment page could list submissions, backups, and groups, perhaps using tabs so they can be listed easily.
There's no need for separate pages for assignments. You really only care about your most recent backups, etc. If there's too much information, this gets annoying to navigate (and I get a ton of UI complaints).
There should be a breadcrumb in the header to help navigate, similar to Gradescope's. The breadcrumb has the form Course > Assignment and the Assignment has a dropdown allowing you to navigate to other assignments in the same class easily.
Not sure if this is necessary without the previous bullet point.
The user should be notified in real time when they or someone in their group submits or adds them to a group.
Yes, this is in the works. (The notification framework will be able to handle this).

**Comment by knrafto** [comment] 2015-02-23 00:06
* The menu that appears on the right should be replaced with a simple dropdown that appears when the user hovers over the header.
    * I don't like the hovering because it might be unintentional and annoying. I think they should have to click on stuff to show intent.
    * You can make the dropdown clickable (like FB) but the current menu is too flashy and intrusive. It blocks me from interacting with the rest of the and takes too long to dismiss.
* Lists (list of courses, list of assignments) should take up less space. Currently each item takes up over half my screen height, and getting to any one item or browsing requires too much scrolling.
    * I don't think it should take up less space- I don't like having a large information density for the student view. If we bubble up active assignments, scrolling goes away.
    * As a user, if I know what assignment or course I want then I want to go there as fast as possible. I want all the information to fit on the page.
* Each assignment should have a separate page. The assignment page could list submissions, backups, and groups, perhaps using tabs so they can be listed easily.
    * There's no need for separate pages for assignments. You really only care about your most recent backups, etc. If there's too much information, this gets annoying to navigate (and I get a ton of UI complaints).
    * I think a separate page is better than the "more info" dropdown. Perhaps use tabs to separate backups, submissions, and groups (e.g. see Github's user profile page). The breadcrumb will make it easy to navigate. I think it's easier than scrolling everywhere.

@Sumukh I did mean site notifications.

Just my $.02. Feel free to close the issue :)

**Comment by Some3141** [comment] 2015-02-23 00:24
Okay, I didn't know that you can make the dropdown clickable (didn't think of Facebook there. XD). I agree with you then- can you make a separate issue?

In terms of having lists and assignments take up less space- I think we both want the same thing but have different solutions for it. I think the main annoyance right now is that there's a lot of scrolling that has to be done, which I think is an issue. One way to fix it would be to put more information on the page- however through experience, we saw that led to a lot of "How do I do [x]?" questions on Piazza and in my inbox, which wasn't fun for me. :-) The second way to fix it would be to have the most recent assignments appear first (e.g. the active ones first, and then the inactive ones sorted by date) @Sumukh is working on this.  Both are reducing scrolling and I think the second way just requires us to think a lot more about the student's shoes, which is definitely a good thing. 

The reason we don't have separate pages for backups, submissions, etc is that it was very confusing for people to navigate. For example, the first few times I was using the staff page (and even sometimes now), I'm not 100% sure where things are. I'm willing to click around and staff generally should since information density is important to them, but students shouldn't be expected to do that.

Before closing, we should all be convinced that everything you brought up is either a non-issue or we make an issue so that it gets done eventually.

**Closed** 2015-07-03 08:34 UTC
