### ISSUE TITLE
`--export` flag does not download late submissions

### ISSUE THREAD

**Issue by jeffreylu017** [Cal-CS-61A-Staff/ok#493] opened 2015-07-02 02:39 UTC
When running `python3 ok --export`, ok does not export all final submissions, but only the last submission before the posted deadline.  I'm not sure what's happening in the backend, but I'm guessing that this is because a submission is marked as final upon submitting only if it is before the deadline, since after I made a [new lab 1 submission](https://ok-server.appspot.com/manage#/submission/6626078391009280) as the user jeffreylu017@gmail.com, and moved the deadline to a later date, I still was downloading my [old submission](https://ok-server.appspot.com/manage#/submission/6285000114700288) back from 6/23.

This is slightly problematic since normally we allow for a small grace period after midnight for straggling homework submissions, as well as late project submissions up to a day late for 2/3 credit.

It would be nice if we could just download all the latest submissions, regardless of when the deadline is, or had an option to the latest submission up to a certain date.  Downloaded submissions include timestamps for when it was submitted anyways, so we can always look at the timestamps and process them however we need to.

**Comment by alvinwan** [comment] 2015-07-02 03:48
Mhm. Try this:

Go to the admin panel > CS61A > search and type the following
```
-assignment "Lab 1" -date --before "2015-06-25"
```
Click "Download Page". (I just fixed a fix to master for "Download All", but it hasn't been deployed yet.)

**Comment by jathak** [comment] 2015-07-02 08:05
The client uses the `final_submission` endpoint when exporting, but I could add an option to instead use the `get_submissions` endpoint if there's a need for it.

**Comment by soumyabasu** [comment] 2015-07-02 08:30
I think the --export should use the final_submission endpoint, so this behavior is probably the right thing to do here. The reason for this is that the final_submission is the thing that gets graded for almost every student.

To support this feature, we should have a separate protocol that is similar to ExportProtocol, but handles grabbing arbitrary submissions. There should be some other command line arguments for common use cases. The search feature on the web interface might be a good place to start there. @jathak - do you want to do this? From what I remember, you have experience making a good command line interface for this?

**Comment by jathak** [comment] 2015-07-02 17:49
Sure. Are there any specific use cases I should make sure to account for?

**Comment by albert12132** [comment] 2015-07-02 18:10
Why not just make `ExportProtocol` handle arbitrary submissions, and make `--final-submissions` a special case? It seems odd that there should be two protocols that both handle exports.

**Comment by soumyabasu** [comment] 2015-07-02 19:32
If it fits in one protocol logically, that's fine.

However, I think the final submission export should be an easy case since that's probably going to be the most common thing that's used.

**Comment by albert12132** [comment] 2015-07-02 19:34
Well, Jeffrey and my impressions of "final_submission" are all final
submissions, including the ones past the deadline. I think this is a case
of a misleading name more than anything.

**Comment by soumyabasu** [comment] 2015-07-02 19:48
The definition of final_submission used to be the last submission, but we consciously decided to change it to "the submission that gets graded" which is the one before the deadline. The reason for this is that a lot of students accidentally resubmit things and end up getting 0s on assignments as a result -- much more than the students for whom buffers are useful. So, I think the final_submission definition should stay as it is.

To solve this issue, we can maybe have a "buffer" flag that allows you to specify a grace period when exporting submissions since these are special cases. We should also have some option like this when autograding- @Sumukh, is this hard to do?

**Comment by jathak** [comment] 2015-07-02 20:04
What about setting the deadline in OK to be the hard deadline after which submissions are counted as late but give students a soft deadline (e.g. tell students an assignment is due at midnight but set the deadline in OK to 1 AM). You could add a soft deadline field to the assignment configuration that's displayed to students in the web interface (so that the hard deadline isn't publicized and students don't try to take advantage of it).

**Comment by Sumukh** [comment] 2015-07-02 20:54
Are you asking to have a buffer period in which late submissions are automatically turned into final submissions? We can do that - however, I think the workflow we had in mind here was that if students want to actually use a later submission - they would have to explicitly say so by promoting their late submission on the web interface. 

The reason we don't allow it automatically is because it was a frequent problem that students were accidentally getting late penalties. 

We can add messaging that the server sends to the OK-client (this submission is late, we are not going to grade it unless you change it...) - or this can be something where the ok-client prompts again - and says do you want us to actually grade it - and the server will then promote it.

**Comment by albert12132** [comment] 2015-07-02 21:03
I'm surprised that students so frequently made the mistake of submitting a late assignment, because they'd have to deliberately use the --submit flag to do so. This was never that big of an issue when we used `glookup`.

If there is a way for students to promote their late submissions, then that's fine. However, last time I checked, the button for promoting final submissions doesn't actually work right now.

I like the ideas for ok-client. We can prompt them from ok-client and mark it for them, but also print out a message explaining how to change it on the website.

**Comment by jeffreylu017** [comment] 2015-07-02 21:30
I like this idea as well.  It's true that students would occasionally submit an extra time accidentally (I guess like using arrow keys to re-enter the last command), so if they are able to explicitly mark a submission as their final submission, then I think it would be more convenient for both sides.

Once we're able to download submissions from ok-server.appspot.com, then we'll also have the option of resolving any incorrect submissions manually as well.

**Comment by soumyabasu** [comment] 2015-07-02 21:46
For glookup, mistaken submissions were harder to make because you had to copy your files over and do a bunch of other stuff. Here, it's the same command for every assignment, so if you're accidentally in a different directory, then you can submit that other assignment. Because we made submission easier, it's also easier to make a mistake.

@jathak - I think that is a potential idea, but the problem is the buffers are very different from course to course. Some courses just have strict deadlines. Others allow slip days. Even for 61A, I accepted the first few labs and stuff last semester very late (like a week or two late) since there were some ok bugs. It's just very difficult to take that into account automatically.

@Sumukh - Yes, this is in that vein. Basically, it would be nice for staff to bulk-promote submissions as final according to the buffer. I doubt most students know about the buffer - some probably were surprised to see their grade was higher. Most students who want to use a different final submission probably want it to be an earlier one rather than a later one.

ok-client changes that require a couple of round trips to the server make me a little nervous (more failure conditions), so we should tell students to change it on the website.

**Comment by soumyabasu** [comment] 2015-07-02 21:47
Oh, also- I think the workflow that we had in mind was for everything to be run by the autograder, and the staff would just mark other submissions as final if a student asks for something different. However, the buffer idea is problematic to do in this manner because a ton of students might be submitting after the buffer.

**Comment by albert12132** [comment] 2015-07-02 21:55
Let's not worry about a buffer. Ultimately, Jeffrey and I just want a way
to be able to export submissions that occur after the deadline so that we
can grade them if necessary.

**Comment by papajohn** [comment] 2015-07-02 22:03
Support two export modes, one for FinalSubmissions and one for latest
Submissions, seems like a reasonable request to me. The second might take
longer b/c the server will have to iterate over the Submissions table.

Does anyone want to accept this Issue & add this new export mode?

**Comment by jathak** [comment] 2015-07-02 22:05
I can do it.

**Comment by jathak** [comment] 2015-07-02 22:43
I've made a pull request for this at [ok-client#105](https://github.com/Cal-CS-61A-Staff/ok-client/issues/105). Adding the `--latest` flag when exporting will download the latest submissions.

**Comment by soumyabasu** [comment] 2015-07-03 20:36
The PR has been merged.

**Closed by soumyabasu** 2015-07-03 20:36 UTC
