### ISSUE TITLE
Fix updating the client version of OK

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/ok#446] opened 2015-05-29 22:31 UTC
@albert12132 writes:
According to Sumukh, the okpy.org page that does this doesn't actually update the version number; it just creates the new version number.

**Comment by albert12132** [comment] 2015-06-06 05:25
This is appears to be a duplicate of #423 .

**Comment by soumyabasu** [comment] 2015-06-19 18:17
Closed via #423

**Closed by soumyabasu** 2015-06-19 18:17 UTC
Labels: duplicate
