### ISSUE TITLE
Deleting a comment prevents adding a comment without refreshing

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#377] opened 2015-02-14 09:58 UTC
This could be a chance to add in the editing feature - by making this an edit icon - performing the delete and creating an input box with the original comment text. Behind the scenes, it'll just follow the same API calls.

**Comment by jordonwii** [comment] 2015-04-17 19:10
@Sumukh I'd be willing to take this one on. Is there a design doc for the editing feature already?

**Comment by Sumukh** [comment] 2015-04-17 22:17
There is not - I'd be happy to talk about it though. Send me an email and we can find a time to meet.

**Comment by papajohn** [comment] 2015-05-29 20:49
Duplicate of #404 ?

**Comment by jordonwii** [comment] 2015-05-30 03:23
@papajohn I think #404 is a dup of this one.

I've got the editing feature (and the fix for this) almost finished. I'll try and wrap them up soon.

**Closed** 2015-07-04 00:49 UTC
Labels: frontend

**Comment by alvinwan** [comment] 2015-07-04 00:51
@jordonwii Turns it out, the problem was twofold: (1) hideBox was still true, even though the button was trying to toggle showComment (2) this behavior was enforced because the comment wasn't actually removed from the page. Just in case you were curious. x)
