### ISSUE TITLE
Continuous autograding should be opt-in

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#974] opened 2016-11-09 22:26 UTC

**Comment by knrafto** [comment] 2016-11-17 06:55
Also, continuous autograding should be opt-in and not automatically enabled by the presence of an autograder key

**Comment by Sumukh** [comment] 2017-02-24 21:43
The posting scores back is a dupe of #840 so I'm renaming this to just be the opt-in.

**Closed** 2017-02-25 08:12 UTC
